import { DisciplineDefinition } from "@/types/domain";

export const DEFAULT_DISCIPLINES: DisciplineDefinition[] = [
  {
    id: "100m-a",
    name: "100 meters",
    disciplineType: "track_lanes",
    usesLanes: true,
    usesHeats: true,
    usesStartOrder: false,
    maxParticipantsPerHeat: 8,
    categoryId: "cat-a",
  },
  {
    id: "200m-a",
    name: "200 meters",
    disciplineType: "track_lanes",
    usesLanes: true,
    usesHeats: true,
    usesStartOrder: false,
    maxParticipantsPerHeat: 8,
    categoryId: "cat-a",
  },
  {
    id: "4x100-a",
    name: "4x100 relay",
    disciplineType: "relay",
    usesLanes: true,
    usesHeats: true,
    usesStartOrder: false,
    maxParticipantsPerHeat: 8,
    categoryId: "cat-a",
    teamSize: 4,
  },
  {
    id: "long-jump-a",
    name: "Long Jump",
    disciplineType: "field",
    usesLanes: false,
    usesHeats: false,
    usesStartOrder: true,
    maxParticipantsPerHeat: 12,
    categoryId: "cat-a",
  },
  {
    id: "shot-put-a",
    name: "Shot Put",
    disciplineType: "field",
    usesLanes: false,
    usesHeats: false,
    usesStartOrder: true,
    maxParticipantsPerHeat: 12,
    categoryId: "cat-a",
  },
];
